# Generated by Django 5.2 on 2025-04-25 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido')),
            ],
        ),
    ]
